base:
  projects: dvc_pipeline_with_iris
  random_state: 42
  target_col: species

data_source:
  git_path: D:\Projects\DVC_pipeline\dvc\data\iris.csv

split:
  dir: dvc/data/split
  train_file: train.csv
  test_file: test.csv
  split_ratio: 0.20

process:
  dir: dvc/data/processed
  train_file: train.csv
  test_file: test.csv

train: 
  n_est: 10

model_dir: model